# Generated by Django 3.0.3 on 2020-02-18 05:44

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Hire_Date', models.DateField(blank=True, null=True)),
                ('Home_Phone', phone_field.models.PhoneField(blank=True, help_text='Home phone number', max_length=31)),
                ('Mobile_Phone', phone_field.models.PhoneField(blank=True, help_text='Mobile phone number', max_length=31)),
                ('Notes', models.CharField(blank=True, max_length=250, null=True)),
                ('Rate_IME', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Rate_AD', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Rate_PR', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Rate_NS', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Rate_EX', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Claimant_Name', models.CharField(max_length=100)),
                ('Claim_Number', models.CharField(blank=True, max_length=20, null=True)),
                ('AssessmentDate', models.DateField(blank=True, null=True)),
                ('AssessmentTime', models.TimeField(blank=True, null=True)),
                ('InvoiceNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('InvoiceDate', models.DateField(blank=True, null=True)),
                ('InvoiceSubtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('InvoiceTax', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('InvoiceTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('InvoicePaid', models.BooleanField(default=False)),
                ('Agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, verbose_name='Clinic Name')),
                ('Address', models.CharField(max_length=150)),
                ('Main_Contact', models.CharField(blank=True, max_length=150, null=True)),
                ('Office_Phone', phone_field.models.PhoneField(blank=True, help_text='Office phone number', max_length=31)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Notes', models.CharField(blank=True, max_length=250, null=True)),
                ('Rate_IME', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Rate_NS', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Home_Phone', phone_field.models.PhoneField(blank=True, help_text='Home phone number', max_length=31)),
                ('Mobile_Phone', phone_field.models.PhoneField(blank=True, help_text='Mobile phone number', max_length=31)),
                ('CMPA', models.IntegerField(blank=True, null=True)),
                ('CPSO', models.IntegerField(blank=True, null=True)),
                ('Notes', models.CharField(blank=True, max_length=250, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('Rate_IME', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Rate_AD', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Rate_PR', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Rate_NS', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Rate_EX', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Abbreviation', models.CharField(blank=True, max_length=4, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Address', models.CharField(max_length=150)),
                ('Office_Phone', phone_field.models.PhoneField(blank=True, help_text='Office phone number', max_length=31)),
                ('Main_Contact', models.CharField(blank=True, max_length=150, null=True)),
                ('Contact_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Contact_Phone', phone_field.models.PhoneField(blank=True, help_text='Main Contact phone number', max_length=31)),
                ('Billing_Contact', models.CharField(blank=True, max_length=150, null=True)),
                ('Billing_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Billing_Phone', phone_field.models.PhoneField(blank=True, help_text='Billing Contact phone number', max_length=31)),
                ('Notes', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Report_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.ReportType')),
                ('Source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Source')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('CheckNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('AppliedBalance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Applied', models.BooleanField(default=False)),
                ('Source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.Source')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillDate', models.DateField(blank=True, null=True)),
                ('BillSubtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('BillTax', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('BillTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('BillPaid', models.BooleanField(default=False)),
                ('DatePaid', models.DateField(blank=True, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setup.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillDate', models.DateField(blank=True, null=True)),
                ('BillTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('BillPaid', models.BooleanField(default=False)),
                ('DatePaid', models.DateField(blank=True, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setup.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Claimant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss')], max_length=4)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Date_Of_Birth', models.DateField()),
                ('Claim_Number', models.CharField(blank=True, max_length=20, null=True)),
                ('Date_Of_Accident', models.DateField(blank=True, null=True)),
                ('Full_Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Source')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='Clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Clinic'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Doctor'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='Report_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.ReportType'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='Source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Source'),
        ),
        migrations.CreateModel(
            name='ApplyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Assessment')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='AgentBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillDate', models.DateField(blank=True, null=True)),
                ('BillTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('BillPaid', models.BooleanField(default=False)),
                ('DatePaid', models.DateField(blank=True, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setup.Assessment')),
            ],
        ),
    ]
