# Generated by Django 3.0.3 on 2020-02-18 05:44

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('home_phone', phone_field.models.PhoneField(blank=True, help_text='Home phone number', max_length=31)),
                ('mobile_phone', phone_field.models.PhoneField(blank=True, help_text='Mobile phone number', max_length=31)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('rate_ime', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rate_ad', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rate_pr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rate_ns', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rate_ex', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimant_name', models.CharField(max_length=100)),
                ('claim_number', models.CharField(blank=True, max_length=20, null=True)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('assessment_time', models.TimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('invoice_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('invoice_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('invoice_paid', models.BooleanField(default=False)),
                ('Agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, verbose_name='Clinic Name')),
                ('address', models.CharField(max_length=150)),
                ('main_contact', models.CharField(blank=True, max_length=150, null=True)),
                ('office_phone', phone_field.models.PhoneField(blank=True, help_text='Office phone number', max_length=31)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('rate_ime', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rate_ns', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('home_phone', phone_field.models.PhoneField(blank=True, help_text='Home phone number', max_length=31)),
                ('mobile_phone', phone_field.models.PhoneField(blank=True, help_text='Mobile phone number', max_length=31)),
                ('cmpa', models.IntegerField(blank=True, null=True)),
                ('cpso', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('rate_ime', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rate_ad', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rate_pr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rate_ns', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rate_ex', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Abbreviation', models.CharField(blank=True, max_length=4, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('office_phone', phone_field.models.PhoneField(blank=True, help_text='Office phone number', max_length=31)),
                ('main_contact', models.CharField(blank=True, max_length=150, null=True)),
                ('Contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', phone_field.models.PhoneField(blank=True, help_text='Main Contact phone number', max_length=31)),
                ('Billing_Contact', models.CharField(blank=True, max_length=150, null=True)),
                ('Billing_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Billing_Phone', phone_field.models.PhoneField(blank=True, help_text='Billing Contact phone number', max_length=31)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.ReportType')),
                ('Source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Source')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('check_number', models.CharField(blank=True, max_length=20, null=True)),
                ('applied_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Applied', models.BooleanField(default=False)),
                ('Source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.Source')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillDate', models.DateField(blank=True, null=True)),
                ('BillSubtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('BillTax', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('BillTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('BillPaid', models.BooleanField(default=False)),
                ('DatePaid', models.DateField(blank=True, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setup.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillDate', models.DateField(blank=True, null=True)),
                ('BillTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('BillPaid', models.BooleanField(default=False)),
                ('DatePaid', models.DateField(blank=True, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setup.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Claimant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss')], max_length=4)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('claim_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_accident', models.DateField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Source')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='Clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Clinic'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Doctor'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='report_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.ReportType'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='Source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Source'),
        ),
        migrations.CreateModel(
            name='ApplyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Assessment')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='AgentBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillDate', models.DateField(blank=True, null=True)),
                ('BillTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('BillPaid', models.BooleanField(default=False)),
                ('DatePaid', models.DateField(blank=True, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setup.Assessment')),
            ],
        ),
    ]
