# Generated by Django 3.0.3 on 2020-02-25 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_auto_20200224_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='claim_number',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='claimant_name',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='source',
        ),
        migrations.AddField(
            model_name='assessment',
            name='claimant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setup.Claimant'),
            preserve_default=False,
        ),
    ]
