# Generated by Django 3.0.3 on 2020-02-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_auto_20200224_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
