# Generated by Django 3.0.3 on 2020-02-28 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_assessment_invoice_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='assessment_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='assessment_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='invoice_balance',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='invoice_paid',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='invoice_subtotal',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='invoice_tax',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='invoice_total',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='report_type',
        ),
        migrations.CreateModel(
            name='SourcePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=20, null=True)),
                ('applied_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('applied', models.BooleanField(default=False)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.Source')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Assessment')),
                ('report_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.ReportType')),
            ],
        ),
        migrations.AlterField(
            model_name='applypayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.SourcePayment'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
