# Generated by Django 3.0.3 on 2020-03-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_auto_20200228_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='applied',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
