# Generated by Django 3.0.3 on 2020-03-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_invoice_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='applied',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
