# Generated by Django 3.0.3 on 2020-03-05 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_auto_20200305_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applypayment',
            old_name='payment',
            new_name='sourcepayment',
        ),
        migrations.RemoveField(
            model_name='applypayment',
            name='assessment',
        ),
        migrations.AddField(
            model_name='applypayment',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setup.Invoice'),
            preserve_default=False,
        ),
    ]
