# Generated by Django 3.0.3 on 2020-03-06 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_auto_20200305_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcepayment',
            old_name='applied_balance',
            new_name='tax',
        ),
    ]
