# Generated by Django 3.0.3 on 2020-03-07 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_auto_20200305_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentbill',
            old_name='bill_paid',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='agentbill',
            old_name='date_paid',
            new_name='paid_date',
        ),
        migrations.RenameField(
            model_name='agentbill',
            old_name='bill_total',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='clinicbill',
            old_name='bill_paid',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='clinicbill',
            old_name='date_paid',
            new_name='paid_date',
        ),
        migrations.RenameField(
            model_name='clinicbill',
            old_name='bill_total',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='doctorbill',
            old_name='bill_paid',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='doctorbill',
            old_name='date_paid',
            new_name='paid_date',
        ),
        migrations.RenameField(
            model_name='doctorbill',
            old_name='bill_subtotal',
            new_name='subtotal',
        ),
        migrations.RenameField(
            model_name='doctorbill',
            old_name='bill_tax',
            new_name='tax',
        ),
        migrations.RenameField(
            model_name='doctorbill',
            old_name='bill_total',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='doctorbill',
            name='assessment',
        ),
        migrations.AddField(
            model_name='doctorbill',
            name='invoice',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='setup.Invoice'),
            preserve_default=False,
        ),
    ]
