# Generated by Django 3.0.3 on 2020-03-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_auto_20200307_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(choices=[('Physician payout', 'Physician payout'), ('Agent payout', 'Agent payout'), ('Clinic rent', 'Clinic rent'), ('Other expense', 'Other expense'), ('Consulting fees', 'Consulting fees')], max_length=100)),
                ('payee', models.CharField(blank=True, max_length=100, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('abbreviation', models.CharField(default='DR', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='sourcepayment',
            name='abbreviation',
            field=models.CharField(default='CR', max_length=2),
        ),
        migrations.AlterField(
            model_name='doctorbill',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
