# Generated by Django 3.0.3 on 2020-03-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0014_auto_20200307_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='abbreviation',
            field=models.CharField(blank=True, default='DR', max_length=2, null=True),
        ),
    ]
