# Generated by Django 3.0.3 on 2020-03-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0015_auto_20200310_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcepayment',
            name='abbreviation',
            field=models.CharField(blank=True, default='CR', max_length=2, null=True),
        ),
    ]
