# Generated by Django 3.0.3 on 2020-03-13 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0016_auto_20200312_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorbill',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.Expense'),
        ),
    ]
