# Generated by Django 3.0.3 on 2020-03-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0017_doctorbill_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, default='Expense', max_length=200, null=True),
        ),
    ]
