# Generated by Django 3.0.3 on 2020-03-13 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0018_auto_20200313_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentbill',
            name='assessment',
        ),
        migrations.AddField(
            model_name='agent',
            name='rate_ar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='agentbill',
            name='invoice',
            field=models.OneToOneField(default=10, on_delete=django.db.models.deletion.CASCADE, to='setup.Invoice'),
            preserve_default=False,
        ),
    ]
