# Generated by Django 3.0.3 on 2020-03-13 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0019_auto_20200313_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicbill',
            name='assessment',
        ),
        migrations.AddField(
            model_name='clinicbill',
            name='invoice',
            field=models.OneToOneField(default=10, on_delete=django.db.models.deletion.CASCADE, to='setup.Invoice'),
            preserve_default=False,
        ),
    ]
