# Generated by Django 3.0.3 on 2020-03-14 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0020_auto_20200313_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentbill',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.Expense'),
        ),
        migrations.AddField(
            model_name='clinicbill',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.Expense'),
        ),
    ]
