# Generated by Django 3.0.3 on 2020-03-14 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0022_auto_20200314_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.Agent'),
        ),
        migrations.AddField(
            model_name='expense',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.Clinic'),
        ),
        migrations.AddField(
            model_name='expense',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.Doctor'),
        ),
    ]
