# Generated by Django 3.0.3 on 2020-05-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0023_auto_20200314_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorbill',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
