# Generated by Django 3.0.3 on 2020-06-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0024_auto_20200516_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimant',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claimant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
