# Generated by Django 3.0.3 on 2020-06-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0026_auto_20200603_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
