# Generated by Django 3.0.3 on 2020-06-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0027_invoice_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
